# seneca.yaml

## Where the samples will be written
save_data: data
## Where the vocab(s) will be written
src_vocab: data/seneca_vocab_src_8
tgt_vocab: data/seneca_vocab_tgt_8
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    seneca:
        path_src: data/seneca_train_src_8
        path_tgt: data/seneca_train_tgt_8
    valid:
        path_src: data/seneca_dev_src_8
        path_tgt: data/seneca_dev_tgt_8
...
