# seneca.yaml

## Where the samples will be written
save_data: data
## Where the vocab(s) will be written
src_vocab: data/seneca_all_src_vocab
tgt_vocab: data/seneca_all_tgt_vocab
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    seneca:
        path_src: data/seneca_all_src
        path_tgt: data/seneca_all_tgt
    valid:
        path_src: data/seneca_other_dev_src_1
        path_tgt: data/seneca_other_dev_tgt_1
...