# seneca.yaml

## Where the samples will be written
save_data: data
## Where the vocab(s) will be written
src_vocab: data/seneca_vocab_src_3
tgt_vocab: data/seneca_vocab_tgt_3
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    seneca:
        path_src: data/seneca_train_src_3
        path_tgt: data/seneca_train_tgt_3
    valid:
        path_src: data/seneca_dev_src_3
        path_tgt: data/seneca_dev_tgt_3
...
