# seneca.yaml

## Where the samples will be written
save_data: data
## Where the vocab(s) will be written
src_vocab: data/seneca_other_vocab_src_6
tgt_vocab: data/seneca_other_vocab_tgt_6
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    seneca:
        path_src: data/seneca_other_train_src_6
        path_tgt: data/seneca_other_train_tgt_6
    valid:
        path_src: data/seneca_other_dev_src_6
        path_tgt: data/seneca_other_dev_tgt_6
...
